### ISSUE TITLE
destructor is not a function error

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-polyfills/ember-destroyable-polyfill#10]
![image](https://user-images.githubusercontent.com/199018/80295249-36c83000-873f-11ea-97c8-1570c42db1b9.png)

buut, I _think_ it's configured properly?

![image](https://user-images.githubusercontent.com/199018/80295254-4d6e8700-873f-11ea-909f-ca24beb44ee5.png)

How this static method is invoked: 
```ts
// from a component
yield ReceiveDataConnection.build(this);
```

the teardown method does exist:
![image](https://user-images.githubusercontent.com/199018/80295336-02a13f00-8740-11ea-913b-74af962142de.png)

**Comment by NullVoxPopuli** [comment]
omg, I'm invoking the teardown during register. lol. now I'm concerned for other reasons.

**Comment by rwjblue** [comment]
Seems reasonable to add an assertion to ensure that the destructor is a function (ideally when it is registered, but also before attempting to call it) 🤔
