### ISSUE TITLE
module state / `assertDestroyablesDestroyed()` leaks state between tests

### ISSUE THREAD

**Issue by buschtoens** [ember-polyfills/ember-destroyable-polyfill#2]
Currently `assertDestroyablesDestroyed()` (and all of this polyfill) relies on module state. 

This causes two issues:

`assertDestroyablesDestroyed()` leaks between test runs, even when the container is reset.

`assertDestroyablesDestroyed()` is incorrect, when running multiple `ApplicationInstance`s in parallel (as happens in FastBoot). Since this function is only available in tests, I don't think this a concern.

I don't really know, how exactly this should be fixed ideally and think that this could be a design flaw in the RFC.

**Comment by rwjblue** [comment]
Check out how ember-lifeline does this here:

https://github.com/ember-lifeline/ember-lifeline/blob/v5.0.0/addon/utils/disposable.ts#L19-L21

https://github.com/ember-lifeline/ember-lifeline/blob/v5.0.0/addon-test-support/setup-lifeline-validation.ts

**Comment by rwjblue** [comment]
The goal in the RFC was to use _exactly_ this style of thing, but that `_setRegisteredDisposables` bit is private so the RFC does **not** explicitly state it.

**Comment by rwjblue** [comment]
I believe that this was fixed over in https://github.com/ember-polyfills/ember-destroyable-polyfill/pull/64
