### ISSUE TITLE
Introduce deprecation warnings on beta/canary ember

### ISSUE THREAD

**Issue by tchak** [ember-polyfills/ember-destroyable-polyfill#55]
Since https://github.com/emberjs/ember.js/pull/19025 this addon triggers deprecation warnings

**Comment by buschtoens** [comment]
Thanks for the heads up!

Form a quick glance, it looks like we could just start exposing the _actual_ destroyable API from that version onward.

**Comment by rwjblue** [comment]
The deprecations on 3.20+ are fixed (as of #70), and just need a release.

@pzuraq / @buschtoens - Would you mind adding me to `npm` so I can release once the other changes I've got cookin' up are done?

**Comment by buschtoens** [comment]
Either @pzuraq already added you by now, or you've already been an owner. :)
<img width="163" alt="image" src="https://user-images.githubusercontent.com/834636/88526173-e392a180-cffb-11ea-9728-4c2a2c8d4b09.png">

**Comment by rwjblue** [comment]
Thank you @buschtoens (and @pzuraq)!

**Comment by rwjblue** [comment]
Resolved in https://github.com/ember-polyfills/ember-destroyable-polyfill/releases/tag/v1.0.0
