### ISSUE TITLE
Not compatible with ember-classic-decorator

### ISSUE THREAD

**Issue by boris-petrov** [ember-polyfills/ember-destroyable-polyfill#78]
[This line](https://github.com/emberjs/ember-classic-decorator/blob/35581575bbf66672099d5228651ae79f5b0e8f17/vendor/classic-decorator/index.js#L148) in `ember-classic-decorator` overrides `require`. Then, when running my app with version 2.0.1 of `ember-modifiers` (which includes `ember-destroyable-polyfill`), [this line](https://github.com/ember-polyfills/ember-destroyable-polyfill/blob/4137d548e90d35c8dc008e3948ddf634c9c7418c/vendor/ember-destroyable-polyfill/register.js#L2) blows up with `require.has is not a function`.

Not sure how to work-around this.

**Comment by rwjblue** [comment]
1. We should file a bug on ember-classic-decorator to fix that (should be straight forward to fix by adding an aliased `require.has = originalRequire.has`)
2. I am working on rewriting the internals here to avoid needing the `require` bit

**Comment by rwjblue** [comment]
Thanks for reporting, hoping to have a PR for that refactor today 🤞
