### ISSUE TITLE
Update ember-lifeline to use this polyfill

### ISSUE THREAD

**Issue by rwjblue** [ember-polyfills/ember-destroyable-polyfill#8]
I'd like to at least spike migrating ember-lifeline to leveraging this polyfill, then we could do the same for ember-concurrency, etc.

/cc @scalvert

**Comment by scalvert** [comment]
Yep, agreed. I can take a stab at migrating lifeline's internals.

**Comment by scalvert** [comment]
I seem to be running into a small snag with this.

```
addon/run-task.ts:12:36 - error TS2307: Cannot find module '@ember/destroyable' or its corresponding type declarations.

12 import { registerDestructor } from '@ember/destroyable';
```

There may be a TS build ordering issue going on here, as the module alias is registered dynamically via the register script in vendor. I'm debugging, but so far I haven't gotten to the bottom of it.

@buschtoens do you know if this works with TS projects that use `ember-cli-typescript`?

**Comment by scalvert** [comment]
Resolved (temporarily) by adding this module to paths in the tsconfig.json:

```json
"paths": {
      "dummy/tests/*": ["tests/*"],
      "dummy/*": ["tests/dummy/app/*", "app/*"],
      "ember-lifeline": ["addon"],
      "ember-lifeline/*": ["addon/*"],
      "ember-lifeline/test-support": ["addon-test-support"],
      "ember-lifeline/test-support/*": ["addon-test-support/*"],
      "@ember/destroyable": ["node_modules/ember-destroyable-polyfill"],
      "*": ["types/*"]
    }
```

**Comment by rwjblue** [comment]
Ya, we should (once we are able to land the changes in ember-lifeline) document the exact `tsconfig.json` that are needed for TypeScript consumers here in the README.

**Comment by scalvert** [comment]
Following up on the tsconfig.json changes I made in lifeline to get this to work:

I added the following to the `paths` object:

```
"paths": {
  // ...
  "@ember/destroyable": ["node_modules/ember-destroyable-polyfill"],
  // ...
}
```

**Comment by rwjblue** [comment]
Awesome, thanks @scalvert!

**Comment by rwjblue** [comment]
Sent a PR for adding docs for that over in #73

Also since https://github.com/ember-lifeline/ember-lifeline/pull/852 is landed, I'm closing this...
