### ISSUE TITLE
TypeError: Ember._registerDestructor is not a function

### ISSUE THREAD

**Issue by nightire** [ember-polyfills/ember-destroyable-polyfill#83]
I'm seeing this error with the latest `ember-modifier@2.0.1`.

<img width="765" alt="截屏2020-08-03 上午6 14 14" src="https://user-images.githubusercontent.com/1104018/89133730-ec7df880-d550-11ea-9dd8-6d2200aea9d0.png">

So I add a breakpoint in the `register.js` file to see if the API has been patched correctly:

<img width="1061" alt="截屏2020-08-03 上午6 20 04" src="https://user-images.githubusercontent.com/1104018/89133782-804fc480-d551-11ea-9042-22eb5ac85442.png">

seems like the `register.js` file is running too late.

**Comment by rwjblue** [comment]
@nightire - The refactor that landed (like ~ 10 minutes ago) in v2.0.0 which should fix the issue are hitting here. https://github.com/ember-modifier/ember-modifier/pull/55 updates ember-modifier and I'll release a 2.1.0 once that PR is green.

**Comment by rwjblue** [comment]
Thanks for the detailed bug report!

**Comment by rwjblue** [comment]
Specifically, it will be fixed by https://github.com/ember-polyfills/ember-destroyable-polyfill/pull/80 (as of that version there is no gap in time).

**Comment by rwjblue** [comment]
Should be fixed now (as of https://github.com/ember-modifier/ember-modifier/releases/tag/v2.1.0)

**Comment by rwjblue** [comment]
Can you test and confirm?

**Comment by nightire** [comment]
@rwjblue it works.

**Comment by rwjblue** [comment]
Awesome, will close this one then 😸
